### ISSUE TITLE
Someone has solved the problem of battery reading information

### ISSUE THREAD

**Issue by Krrrrrik** [olm3ca/Surface-Laptop-Go#1]
I found out on a social platform in Chinese mainland that someone had compiled kexts and uploaded it to Github, not knowing if you could fix it. 

https://github.com/Xiashangning/BigSurface

And can you share your EFI?

**Comment by olm3ca** [comment]
That is for the regular Surface, so it's good for reference but the hardware is different. Sleep is implemented differently on this machine and is the only thing not working too well. 

[Here's an EFI](https://www.dropbox.com/s/vadi7vu2cdgu65r/EFI.zip?dl=0) that worked for me on Big Sur, but you'll need to add in your own serial and I can't guarantee it'll work for you.

**Comment by Krrrrrik** [comment]
Thank you for sharing EFI, I'll try it out and see if it works. Someone on that social platform mentioned that his Surface Laptop Go's power information reading was correct.

**Comment by Krrrrrik** [comment]
Just by the way, forget to ask what your OC version number is

**Comment by olm3ca** [comment]
This was built with either OC 0.7.4 or 0.7.5 I can't remember. Please keep me posted on the battery readout issue, that would be such a great advancement and make it way more usable!

**Comment by BILLFANLL** [comment]
> That is for the regular Surface, so it's good for reference but the hardware is different. Sleep is implemented differently on this machine and is the only thing not working too well.
> 
> [Here's an EFI](https://www.dropbox.com/s/vadi7vu2cdgu65r/EFI.zip?dl=0) that worked for me on Big Sur, but you'll need to add in your own serial and I can't guarantee it'll work for you.
that
I have tried this EFI, USBMaps.kext is not working, no sound and sometimes igpu fail to load during last stage. bluetooth can be searched, but it can't be connected.I will try to fix and upload it

**Comment by olm3ca** [comment]
@BILLFANLL - USBMaps is specific to the USB devices I mapped on my device, so you can update that easily for your machine. Sound requires a fix on Big Sur. Details are in the instructions, see step 2, second bullet.

**Comment by BILLFANLL** [comment]
Thanks @olm3ca .Have you ever encountered stuck after the [igpu] code during the boot process, the location of the code stuck is different each time.  But I can feel it is the gpu loading problem.  I only have about a 1/4 chance of being able to boot successfully. Have you solved this problem?

**Comment by olm3ca** [comment]
Hmm, can't say I had a 1/4 success rate, I could boot every time. Sometimes it would be glitchy - the Apple logo right before the user login with change colors for example. You may want to try different settings in device properties for the iGPU based on the OC guide.

**Comment by dclive** [comment]
> That is for the regular Surface, so it's good for reference but the hardware is different. Sleep is implemented differently on this machine and is the only thing not working too well.

Testing with Monterey, 12.5.1. 

Do you have an updated version of that EFI?  There's no "BOOT" folder in there, so I had to supply my own, and then I had to bring the rest of the files up to the appropriate version of OpenCore to keep everything in sync; with OC86 (and using OCAT to handle the update), and making (near as I can tell) no other changes, when I boot up it loads for a bit, a few walls of text, then the graphics go haywire a bit, I see distorted text, and a NOT symbol on the screen.  The boot process then stops. 

Any ideas?  Does anyone have a working EFI for Surface Laptop Go they can share, even without BigSurface.kext in it?  (I didn't add it for this test.) 

It would really help to have a rock solid starting point with a current OC EFI.  Anyone?

**Comment by BILLFANLL** [comment]
Please refer to https://github.com/acidanthera/OpenCorePkg

And install guide https://dortania.github.io/OpenCore-Install-Guide/

> > That is for the regular Surface, so it's good for reference but the hardware is different. Sleep is implemented differently on this machine and is the only thing not working too well.
> 
> 
> 
> Testing with Monterey, 12.5.1. 
> 
> 
> 
> Do you have an updated version of that EFI?  There's no "BOOT" folder in there, so I had to supply my own, and then I had to bring the rest of the files up to the appropriate version of OpenCore to keep everything in sync; with OC86 (and using OCAT to handle the update), and making (near as I can tell) no other changes, when I boot up it loads for a bit, a few walls of text, then the graphics go haywire a bit, I see distorted text, and a NOT symbol on the screen.  The boot process then stops. 
> 
> 
> 
> Any ideas?  Does anyone have a working EFI for Surface Laptop Go they can share, even without BigSurface.kext in it?  (I didn't add it for this test.) 
> 
> 
> 
> It would really help to have a rock solid starting point with a current OC EFI.  Anyone?

**Comment by dclive** [comment]
If you don't have anything, that's OK; we all know where the guide is. 

I've added an early version of my Surface Laptop Go guide to my repository.  Anyone is welcomed to view it and comment; it will get better in the coming days.  Current issues with sleep (or wake, really) not working, and brightness is an issue.

**Comment by BILLFANLL** [comment]
Yes, brightness lead to sleep issue, I have tried many time, however, brightness still not working when wake up.

**Comment by dclive** [comment]
https://github.com/dclive/SurfaceLaptopGo - I've now fixed all brightness and sleep issues.  USB mapping, turns out, is a wonderful thing.

**Comment by dclive** [comment]
In later testing, it seems wake works if on mains power, but on battery, not so much.  Testing is ongoing.  
<Later edit> : All fixed.  A good EFI is in my responsitory, v1.1.
