### ISSUE TITLE
Can't get to installer - booting screen garbled

### ISSUE THREAD

**Issue by felixityC** [olm3ca/Surface-Laptop-Go#2]
I have upgraded my SLGo with a 512GB Caldigit Toshiba drive.

Win10 is installed first, then I shrunk the partition to allow for Big Sur installation.

I made my boot UFI for installer USB with Dortania's guide for IceLake laptop. But it fails to get to the installer and the boot text screen ends up garbled... 

I then tried to use your EFI folder, seeing it is the same device. Changed the PlatformInfo details, but I am still ending up unable to boot to installer.

Having searched around the net, couldn't find anyone else successful installing Big Sur 11.6.2 on this device.

Could you kindly help?? Thank you.

**Comment by felixityC** [comment]
Could you tell me which Big Sur version you are on? 

On top of that I am using OC 0.78

**Comment by olm3ca** [comment]
Big Sur version 11.6 and whatever OC is most recent is what you should use.

Did you turn off bitlocker in security settings at boot? Meaning, do you get the red bar at the top with the unlocked symbol when you turn on the machine? 

Make sure you follow the security steps in the guide. https://github.com/olm3ca/Surface-Laptop-Go#part-1-disable-bitlocker-tpm-and-partition-your-ssd

**Comment by felixityC** [comment]
Thank you for your reply.

Yes, I have followed your guide, and disabled bitlocker. I have the red bar with unlocked symbol during post.

I have rebuilt the OC EFI from Dortania, tried some of the troubleshooting flags, but I am still stuck. I even did a USB mapping to ensure it wasn't USB issue. No luck~

Is there any chance you could share the latest EFI folder so I could compare your settings, as well as test to see if it works?

**Comment by olm3ca** [comment]
This is the last EFI I have, as I switched to Linux / Win11 dual boot after I got this working.

Please confirm when you've downloaded it as this version has the serial I was using. It doesn't matter anymore to me, but I'd prefer to not keep this EFI online. Hope it helps you. It booted just fine for me.

**Comment by felixityC** [comment]
thank you I appreciate your generosity, I managed to get the setup working before you uploaded the EFI.

It turns out the problem was NVRAM, all I had to do was clear it and everything worked~

I have downloaded your EFI - there is also a copy in your dropbox that you might want to remove as well. I will only use what you have provided as means to compare notes with what I have prepared myself.

As you have mentioned, sleep and energy management does not work. Bluetooth appears to work but it will not find any devices.

Is a shame you are no longer working on this project - but thanks to you I now have a semi-working Surface Mac Laptop! Thank you~

**Comment by olm3ca** [comment]
Cool, glad it's working for you now! Yeah without sleep it was kind of frustrating. I hope there's a fix for that. If you do find some way to do it let me know. I think it has to do with power / battery stuff (which also impacts the touchpad use).

**Comment by olm3ca** [comment]
Oh and @felixityC - I still use the laptop, so I'll jump back in someday for sure.

**Comment by Mo0dja** [comment]
> thank you I appreciate your generosity, I managed to get the setup working before you uploaded the EFI.
> 
> It turns out the problem was NVRAM, all I had to do was clear it and everything worked~
> 
> I have downloaded your EFI - there is also a copy in your dropbox that you might want to remove as well. I will only use what you have provided as means to compare notes with what I have prepared myself.
> 
> As you have mentioned, sleep and energy management does not work. Bluetooth appears to work but it will not find any devices.
> 
> Is a shame you are no longer working on this project - but thanks to you I now have a semi-working Surface Mac Laptop! Thank you~

Hi, 

can you please send me the EFI file that works for you? 
I own the same machine and I am struggled weeks long to have it run under macOS without success... I want to compare your file with mine to find what I've done wrong...

Thanks so much for your reply.

**Comment by felixityC** [comment]
Sorry I haven’t used the surface laptop go  for Mac Os for a long time, due to issues with compatibility.

I spent a fair amount of time trying to get the sleep and power optimisations to work but it simple weren't possible.

The laptop, when running Big Sur, drained battery fast, along with poor screen brightness, choppy touchpad, Bluetooth that didn't pair anything. The breaker was no sleep, when you would accidentally close the lid and had to hard reset so I just stayed in Windows.

I did find someone producing a kext called big surface laptop, that would work just like the one mentioned here, you could give that a go and see how far you can get:

https://github.com/Xiashangning/BigSurface <https://github.com/Xiashangning/BigSurface>

I no longer have the EFI as I didn’t keep any backups, with the issues mentioned above I was certain I wouldn't be using Mac OS on this laptop, sorry about that...

Good luck!



On Fri, Oct 28, 2022 at 2:13 AM, Mo0dja
***@***.***> wrote:

thank you I appreciate your generosity, I managed to get the setup working before you uploaded the EFI.

It turns out the problem was NVRAM, all I had to do was clear it and everything worked~

I have downloaded your EFI - there is also a copy in your dropbox that you might want to remove as well. I will only use what you have provided as means to compare notes with what I have prepared myself.

As you have mentioned, sleep and energy management does not work. Bluetooth appears to work but it will not find any devices.

Is a shame you are no longer working on this project - but thanks to you I now have a semi-working Surface Mac Laptop! Thank you~

Hi,

can you please send me the EFI file that works for you?
I own the same machine and I am struggled weeks long to have it run under macOS without success... I want to compare your file with mine to find what I've done wrong...

Thanks so much for your reply.
