### ISSUE TITLE
Keyboard, Sound & Touchpad dont work

### ISSUE THREAD

**Issue by alex90do** [olm3ca/Surface-Laptop-Go#3]
![Bildschirmfoto 2022-05-15 um 16 48 53](https://user-images.githubusercontent.com/77961083/168473717-36e509c7-0657-4496-ba55-17150e913add.png)

**Comment by olm3ca** [comment]
Simple fix for the keyboard and touchpad, [VoodooPS2](https://github.com/acidanthera/VoodooPS2) is needed. 
Sound works, but follow the guide more closely.
