### ISSUE TITLE
Plist for iGPU

### ISSUE THREAD

**Issue by sjsaes** [olm3ca/Surface-Laptop-Go#4]
You've removed the files from the directory, however, you also removed the .plist file you included at some point that the iGPU requires. Can you upload it somewhere, either in this repo or on another cloud storage medium?

**Comment by olm3ca** [comment]
I'm not sure I'm following you. The portion of the .plist related to the iGPU is [here](https://github.com/olm3ca/Surface-Laptop-Go/blob/main/iGPU.plist). If you're asking for the full config.plist, I'm not able to share that, you should build it yourself following the Dortania OC guide.

**Comment by sjsaes** [comment]
Hmm, looks like it had a bug when I loaded the page. It didn't show up, but I assume it's got something to do with my browser/internet connection. Thanks!
