### ISSUE TITLE
Unable to set TPM off

### ISSUE THREAD

**Issue by peppearci** [olm3ca/Surface-Laptop-Go#5]
In UEFI mode, there's no option to disable TPM . I can only choose to enable, disable or partially disable the Secure Boot mode (i think it should be disabled, am I right?).
Is TPM disabling mandatory to proceed with the guide? Bitlocker is already disabled.

Opencore works with secure boot disabled, bitlocker disabled, tpm not activated (no option in uefi)

**Comment by olm3ca** [comment]
You should disable secure boot. Otherwise it will be challenging to use opencore
